# CircleCI 2.0 configuration
version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: nathanielc/docker-client
    working_directory: ~/kapacitor
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - run:
          name: Tests
          command: |
            ./circle-test.sh

# This is old Circle 1.0 syntax but is should work as per
# https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/8
deployment:
  release:
    tag: /v[0-9]+(\.[0-9]+){2}(-(rc|beta)[0-9]+)?/
    commands:
      - ./build.sh --debug --clean --generate --package --package-udfs --upload --bucket=dl.influxdata.com/kapacitor/releases --platform=all --arch=all --release
